# Generated by Django 3.1.4 on 2020-12-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201231_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_data',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Sports', 'Sports'), ('Business', 'Business'), ('WordPress', 'WordPress'), ('Food', 'Food'), ('Writing', 'Writing'), ('Cars', 'Cars'), ('Music', 'Music'), ('Games', 'Games'), ('Movies', 'Movies'), ('Books', 'Books'), ('Fitness', 'Fitness'), ('Mom', 'Mom'), ('Travel', 'Travel'), ('Current Events', 'Current Events'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('DIY', 'DIY'), ('Politics', 'Politics'), ('Parenting', 'Parenting'), ('Pets', 'Pets')], default='', max_length=200),
        ),
    ]
